import 'barcode_utils.dart';

/// Curated Australian / common supermarket products used as the offline
/// source of truth for barcode lookup.
///
/// Prefer real EAN-13 barcodes verified via Open Food Facts or prior app
/// scans. Synthetic `930060500000x` demo aliases are limited to a small
/// aligned set for offline tests — do not invent additional fake barcodes.
class AustralianCuratedProductDatabase {
  AustralianCuratedProductDatabase._();

  /// Lookup a curated product, including UPC/EAN/GTIN variants.
  static Map<String, dynamic>? lookup(String barcode) {
    for (final candidate in BarcodeUtils.lookupCandidates(barcode)) {
      final entry = products[candidate];
      if (entry != null) return Map<String, dynamic>.from(entry);
    }
    return null;
  }

  /// Mutable map so test helpers can add entries at runtime.
  static final Map<String, Map<String, dynamic>> products = {
    // -------------------------------------------------------------------------
    // Real Australian barcodes (verified / previously scanned)
    // -------------------------------------------------------------------------
    '9310155000710': {
      'name': 'La Pasta Carbonara Flavour Pasta and Sauce',
      'brand': 'San Remo',
      'ingredients': [
        'durum wheat semolina',
        'water',
        'salt',
        'cream',
        'parmesan cheese',
        'bacon',
        'onion',
        'garlic',
        'black pepper',
        'parsley',
        'vegetable oil',
        'milk solids',
        'wheat flour',
        'gluten',
        'preservative',
        'antioxidant',
        'natural flavour',
        'artificial flavour',
        'may contain egg',
      ],
      'allergens': ['wheat', 'milk', 'gluten'],
      'mayContainItems': ['Egg'],
      'crossContamination': ['egg'],
      'isAustralianProduct': true,
      'image': null,
    },
    // Twin snack-pack barcode from Open Food Facts (2 x 170 g). Ingredients
    // matched to Goulburn Valley Peaches in Juice label (same brand family).
    '9310093999893': {
      'name': 'Peaches in Juice',
      'brand': 'Goulburn Valley',
      'ingredients': [
        'australian grown sliced peaches (62%)',
        'refined fruit juice',
        'antioxidant (ascorbic acid)',
      ],
      'allergens': <String>[],
      'mayContainItems': <String>[],
      'crossContamination': <String>[],
      'isAustralianProduct': true,
      'image':
          'https://images.openfoodfacts.org/images/products/931/009/399/9893/front_en.3.400.jpg',
    },
    '9316401202464': {
      'name': 'Bhuja Original Mix',
      'brand': 'Bhuja',
      'ingredients': [
        'noodles and chips (51%) (yellow peas, chickpeas, hi-oleic sunflower and/or canola oil, rice, potato, tapioca, salt, sesame, cumin)',
        'peas (coconut oil)',
        'peanuts',
        'sultanas',
        'hi-oleic sunflower and/or canola oil',
        'salt',
        'spices (fennel, chilli, turmeric, paprika)',
        'maltodextrin',
        'sugar',
      ],
      'allergens': ['peanuts', 'sesame'],
      'mayContainItems': ['Tree Nuts', 'Soy'],
      'traces_tags': ['en:nuts', 'en:soybeans'],
      'traces': 'nuts, soybeans',
      'crossContamination': ['tree nuts', 'soy'],
      'isAustralianProduct': true,
      'image': null,
    },
    '9310072000275': {
      'name': 'Arnott\'s Mint Slice',
      'brand': 'Arnott\'s',
      'ingredients': [
        'sugar',
        'wheat flour',
        'palm oil',
        'cocoa mass',
        'milk solids',
        'butter',
        'cocoa',
        'emulsifiers (soy lecithin)',
        'salt',
        'colour (caramel)',
        'raising agents (sodium bicarbonate)',
        'natural flavouring',
      ],
      'allergens': ['gluten', 'milk', 'soy', 'wheat'],
      'mayContainItems': ['Egg', 'Tree Nuts', 'Peanuts', 'Sesame'],
      'traces_tags': ['en:eggs', 'en:peanuts', 'en:sesame-seeds'],
      'traces': 'eggs, peanuts, sesame seeds',
      'crossContamination': ['egg', 'tree nuts', 'peanuts', 'sesame'],
      'isAustralianProduct': true,
      'image': null,
    },
    '9310072013312': {
      'name': 'Arnott\'s Mint Slice Family Pack',
      'brand': 'Arnott\'s',
      'ingredients': [
        'dark chocolate (37%) (sugar, cocoa mass, cocoa butter, vegetable oil (contains soy), milk solids, emulsifiers (soy lecithin, e476), flavour, salt)',
        'sugar',
        'wheat flour',
        'vegetable oil (antioxidant (e307b from soy))',
        'starch (wheat)',
        'cocoa powder',
        'salt',
        'food colour (caramel iii)',
        'baking powder',
        'peppermint oil (0.04%)',
        'emulsifier (soy lecithin)',
        'may contain traces of egg, tree nuts, peanuts, sesame',
      ],
      'allergens': ['gluten', 'milk', 'soy', 'wheat'],
      'mayContainItems': ['Egg', 'Tree Nuts', 'Peanuts', 'Sesame'],
      'traces_tags': ['en:eggs', 'en:peanuts', 'en:sesame-seeds'],
      'traces': 'eggs, peanuts, sesame seeds',
      'crossContamination': ['egg', 'tree nuts', 'peanuts', 'sesame'],
      'isAustralianProduct': true,
      'image': null,
    },
    '931007201332': {
      'name': 'Arnott\'s Mint Slice Family Pack',
      'brand': 'Arnott\'s',
      'ingredients': [
        'dark chocolate (37%) (sugar, cocoa mass, cocoa butter, vegetable oil (contains soy), milk solids, emulsifiers (soy lecithin, e476), flavour, salt)',
        'sugar',
        'wheat flour',
        'vegetable oil (antioxidant (e307b from soy))',
        'starch (wheat)',
        'cocoa powder',
        'salt',
        'food colour (caramel iii)',
        'baking powder',
        'peppermint oil (0.04%)',
        'emulsifier (soy lecithin)',
        'may contain traces of egg, tree nuts, peanuts, sesame',
      ],
      'allergens': ['gluten', 'milk', 'soy', 'wheat'],
      'mayContainItems': ['Egg', 'Tree Nuts', 'Peanuts', 'Sesame'],
      'traces_tags': ['en:eggs', 'en:peanuts', 'en:sesame-seeds'],
      'traces': 'eggs, peanuts, sesame seeds',
      'crossContamination': ['egg', 'tree nuts', 'peanuts', 'sesame'],
      'isAustralianProduct': true,
      'image': null,
    },
    '9352042002827': {
      'name': 'Bega Peanut Butter Crunchy',
      'brand': 'Bega',
      'ingredients': [
        'roasted peanuts (86%)',
        'vegetable oil (antioxidant (320))',
        'sugar',
        'salt',
      ],
      'allergens': ['peanuts'],
      'mayContainItems': ['Tree Nuts', 'Sesame'],
      'crossContamination': ['tree nuts', 'sesame'],
      'isAustralianProduct': true,
      'image': null,
    },
    '9310072026299': {
      'name': 'Arnott\'s Shapes Savoury',
      'brand': 'Arnott\'s',
      'ingredients': [
        'wheat flour',
        'vegetable oil',
        'cheese',
        'sesame seeds',
        'salt',
        'vegetable protein extract',
        'yeast',
        'spices',
        'glucose',
        'baking powder',
        'natural flavour',
        'wheat starch',
        'onion powder',
        'food colours (cochineal, turmeric)',
        'antioxidant (e300)',
      ],
      'allergens': ['wheat', 'gluten', 'milk', 'sesame'],
      'mayContainItems': ['Egg', 'Tree Nuts', 'Peanuts', 'Pine Nut'],
      'traces_tags': ['en:eggs', 'en:nuts', 'en:peanuts', 'en:pine-nut'],
      'traces': 'eggs, nuts, peanuts, pine nut',
      'crossContamination': ['egg', 'tree nuts', 'peanuts'],
      'isAustralianProduct': true,
      'image': null,
    },
    // Same Arnott's Bizza Shapes pack: 9310072037493 is the scanned EAN;
    // 9310072037496 is the sibling code treated as the same product.
    '9310072037496': _arnottsBizzaShapes(),
    '9310072037493': _arnottsBizzaShapes(),
    '9334169005004': {
      'name': 'Test Product',
      'brand': 'Test Brand',
      'ingredients': [
        'wheat flour',
        'sugar',
        'vegetable oil',
        'salt',
        'yeast',
        'milk powder',
        'egg powder',
        'soy lecithin',
        'peanut oil',
      ],
      'allergens': ['wheat', 'milk', 'egg', 'soy', 'peanut'],
      'mayContainItems': [],
      'crossContamination': [],
      'isAustralianProduct': true,
      'image': null,
    },
    '5411600755': {
      'name': 'Cauliflower Puffs - Sea Salt',
      'brand': 'Temole',
      'ingredients': [
        'cauliflower',
        'brown rice',
        'rice bran oil',
        'sea salt',
        'may contain almond',
        'may contain cashew',
        'may contain pistachio',
      ],
      'allergens': [],
      'mayContainItems': ['Almond', 'Cashew', 'Pistachio'],
      'crossContamination': ['tree nuts'],
      'isAustralianProduct': true,
      'image': null,
    },
    '9348219004749': {
      'name': 'Mini Rice Cakes (Caramel White Choc Topped)',
      'brand': 'Table Of Plenty',
      'ingredients': [
        'caramelised white chocolate (60%)',
        'sugar',
        'vegetable fat',
        'milk solids',
        'stabiliser (492)',
        'emulsifier (soy lecithin)',
        'emulsifier (476)',
        'cocoa solids',
        'salt',
        'wholegrain brown rice (40%)',
        'may contain peanut',
        'may contain tree nuts',
        'may contain sesame',
        'may contain sulphites',
      ],
      'allergens': ['milk', 'soy'],
      'mayContainItems': ['Peanut', 'Tree Nuts', 'Sesame', 'Sulphites'],
      'crossContamination': ['peanuts', 'tree nuts', 'sesame', 'sulfites'],
      'isAustralianProduct': true,
      'image': null,
    },
    '9315991023596': {
      'name': 'Vege Deli Chips - Purple & Orange Sweet Potato + Taro',
      'brand': 'Ajitas',
      'ingredients': [
        'orange sweet potato',
        'purple sweet potato',
        'taro',
        'vegetable oil',
        'seasoning (3.5%)',
        'maltodextrin (tapioca starch)',
        'salt',
        'sugar',
        'yeast extract',
        'garlic powder',
      ],
      'allergens': [],
      'mayContainItems': [],
      'crossContamination': [],
      'isAustralianProduct': true,
      'image': null,
    },

    // -------------------------------------------------------------------------
    // Expanded real AU supermarket products (OFF-verified barcodes)
    // -------------------------------------------------------------------------
    '9310072010816': {
      'name': 'Arnott\'s Tim Tam Original',
      'brand': 'Arnott\'s',
      'ingredients': [
        'milk chocolate (38%) (sugar, milk solids, cocoa butter, cocoa mass, vegetable oil, emulsifiers (soy lecithin, e476), flavour)',
        'wheat flour',
        'sugar',
        'vegetable oil (contains soy)',
        'golden syrup',
        'food colours (caramel iii, beet red, cochineal, annatto)',
        'cocoa powder',
        'salt',
        'baking powder',
        'emulsifier (soy lecithin)',
        'flavour',
      ],
      'allergens': ['gluten', 'milk', 'soy', 'wheat'],
      'mayContainItems': ['Egg', 'Tree Nuts', 'Peanuts', 'Sesame'],
      'crossContamination': ['egg', 'tree nuts', 'peanuts', 'sesame'],
      'processingFacility': 'Facility processes: wheat, milk, soy, egg, nuts, sesame',
      'isAustralianProduct': true,
      'image': null,
    },
    '9352042000328': {
      'name': 'Vegemite',
      'brand': 'Bega',
      'ingredients': [
        'yeast extract (from barley and wheat)',
        'salt',
        'mineral salt (508)',
        'malt extract (from barley)',
        'colour (150c)',
        'flavours',
        'niacin',
        'thiamine',
        'riboflavin',
        'folate',
      ],
      'allergens': ['gluten', 'wheat', 'barley'],
      'mayContainItems': [],
      'crossContamination': [],
      'isAustralianProduct': true,
      'image': null,
    },
    '9352042004234': {
      'name': 'Vegemite 40% Less Salt',
      'brand': 'Bega',
      'ingredients': [
        'yeast extract (wheat, barley)',
        'natural colour (150a)',
        'humectant (422)',
        'mineral salt (508)',
        'salt',
        'malt extract (barley)',
        'flavours',
        'niacin',
        'thiamine',
        'vitamin b6',
        'riboflavin',
        'folate',
      ],
      'allergens': ['gluten', 'wheat', 'barley'],
      'mayContainItems': [],
      'crossContamination': [],
      'isAustralianProduct': true,
      'image': null,
    },
    '9300652010794': {
      'name': 'Weet-Bix',
      'brand': 'Sanitarium',
      'ingredients': [
        'wholegrain wheat (97%)',
        'raw sugar',
        'salt',
        'barley malt extract',
        'vitamins (niacin, thiamin, riboflavin, folate)',
        'mineral (iron)',
      ],
      'allergens': ['wheat', 'gluten', 'barley'],
      'mayContainItems': ['Lupin'],
      'traces_tags': ['en:lupin'],
      'traces': 'lupin',
      'crossContamination': ['lupin'],
      'isAustralianProduct': true,
      'image': null,
    },
    '9300605126527': {
      'name': 'Milo',
      'brand': 'Nestlé',
      'ingredients': [
        'extract of malt barley or malt barley and rice (38%)',
        'milk solids',
        'sugar',
        'cocoa',
        'choc malt blend (soy)',
        'minerals (calcium, iron)',
        'vitamins (c, b3, b6, b2, d, b12)',
      ],
      'allergens': ['milk', 'soy', 'gluten', 'barley'],
      'mayContainItems': [],
      'crossContamination': [],
      'isAustralianProduct': true,
      'image': null,
    },
    '9300617304715': {
      'name': 'Cadbury Dairy Milk Chocolate',
      'brand': 'Cadbury',
      'ingredients': [
        'full cream milk',
        'sugar',
        'cocoa mass',
        'milk solids',
        'cocoa butter',
        'emulsifiers (soy lecithin, 476)',
        'flavours',
        'contains milk, soy',
        'may contain wheat, gluten, peanuts, tree nuts',
      ],
      'allergens': ['milk', 'soy'],
      'mayContainItems': ['Wheat', 'Gluten', 'Peanuts', 'Tree Nuts'],
      'traces_tags': ['en:gluten', 'en:nuts', 'en:peanuts'],
      'traces': 'gluten, nuts, peanuts',
      'crossContamination': ['wheat', 'gluten', 'peanuts', 'tree nuts'],
      'isAustralianProduct': true,
      'image': null,
    },
    '9310015241888': {
      'name': 'Smith\'s Original Crinkle Cut Chips',
      'brand': 'Smith\'s',
      'ingredients': [
        'potatoes',
        'canola oil',
        'sunflower oil',
        'salt',
        'antioxidants (tocopherols, ascorbic acid, citric acid)',
        'rosemary extract',
      ],
      'allergens': [],
      'mayContainItems': ['Milk', 'Wheat'],
      'crossContamination': ['milk', 'wheat'],
      'isAustralianProduct': true,
      'image': null,
    },
    '9311493003388': {
      'name': 'Bundaberg Ginger Beer',
      'brand': 'Bundaberg',
      'ingredients': [
        'carbonated water',
        'cane sugar',
        'ginger root',
        'natural flavours',
        'acid (citric acid)',
        'yeast',
        'preservatives (202, 211)',
        'antioxidant (ascorbic acid)',
      ],
      'allergens': [],
      'mayContainItems': [],
      'crossContamination': [],
      'isAustralianProduct': true,
      'image': null,
    },
    '9310179006668': {
      'name': 'Golden Circle Pineapple Juice',
      'brand': 'Golden Circle',
      'ingredients': [
        'pineapple juice and reconstituted pineapple juice (96%)',
        'sugar',
        'vitamin c',
      ],
      'allergens': [],
      'mayContainItems': [],
      'crossContamination': [],
      'isAustralianProduct': true,
      'image': null,
    },
    '9310072026404': {
      'name': 'Arnott\'s Jatz Original',
      'brand': 'Arnott\'s',
      'ingredients': [
        'wheat flour',
        'vegetable oil',
        'sugar',
        'salt',
        'malt extract (from barley)',
        'baking powder',
        'yeast',
        'antioxidants (e307b from soy, e304)',
        'emulsifier (soy lecithin)',
      ],
      'allergens': ['gluten', 'wheat', 'soy', 'barley'],
      'mayContainItems': ['Egg', 'Milk', 'Tree Nuts', 'Peanuts', 'Sesame'],
      'traces_tags': [
        'en:eggs',
        'en:milk',
        'en:nuts',
        'en:peanuts',
        'en:sesame-seeds',
      ],
      'traces': 'eggs, milk, nuts, peanuts, sesame seeds',
      'crossContamination': ['egg', 'milk', 'tree nuts', 'peanuts', 'sesame'],
      'isAustralianProduct': true,
      'image': null,
    },
    '9310060011030': {
      'name': 'Uncle Tobys Traditional Rolled Oats',
      'brand': 'Uncle Tobys',
      'ingredients': [
        '100% uncle tobys whole grain rolled oats',
        'may contain other gluten containing ingredients and lupin',
      ],
      'allergens': ['gluten', 'oats'],
      'mayContainItems': ['Wheat', 'Barley', 'Rye', 'Lupin'],
      'traces_tags': ['en:lupin'],
      'traces': 'lupin',
      'crossContamination': ['wheat', 'barley', 'rye', 'lupin'],
      'isAustralianProduct': true,
      'image': null,
    },
    '9310060012037': {
      'name': 'Uncle Tobys Quick Oats',
      'brand': 'Uncle Tobys',
      'ingredients': [
        'whole grain rolled oats',
      ],
      'allergens': ['gluten', 'oats'],
      'mayContainItems': ['Wheat', 'Lupin'],
      'crossContamination': ['wheat', 'lupin'],
      'isAustralianProduct': true,
      'image': null,
    },
    '9310015240614': {
      'name': 'Red Rock Deli Sea Salt Chips',
      'brand': 'Red Rock Deli',
      'ingredients': [
        'potatoes',
        'canola oil',
        'salt',
        'sunflower oil',
        'antioxidants (tocopherols, ascorbic acid, rosemary extract, citric acid)',
      ],
      'allergens': [],
      'mayContainItems': ['Milk'],
      'crossContamination': ['milk'],
      'isAustralianProduct': true,
      'image': null,
    },
    '9310988009638': {
      'name': 'Kettle Original Sea Salt Chips',
      'brand': 'Kettle',
      'ingredients': [
        'potatoes',
        'sunflower oil and/or canola oil',
        'salt',
      ],
      'allergens': [],
      'mayContainItems': ['Milk', 'Soy'],
      'traces_tags': ['en:milk', 'en:soybeans'],
      'traces': 'milk, soybeans',
      'crossContamination': ['milk', 'soy'],
      'isAustralianProduct': true,
      'image': null,
    },
    '9310053105357': {
      'name': 'Mainland Extra Tasty Cheese',
      'brand': 'Mainland',
      'ingredients': [
        'milk',
        'salt',
        'cultures',
        'enzyme (rennet)',
      ],
      'allergens': ['milk'],
      'mayContainItems': [],
      'crossContamination': [],
      'isAustralianProduct': true,
      'image': null,
    },
    '9310012021049': {
      'name': 'MasterFoods Tomato Sauce',
      'brand': 'MasterFoods',
      'ingredients': [
        'tomatoes (from paste) 79%',
        'sugar',
        'salt',
        'acidity regulator (acetic acid)',
        'onion',
        'spice extract',
        'may contain: peanut',
      ],
      'allergens': [],
      'mayContainItems': ['Peanut'],
      'traces_tags': ['en:peanuts'],
      'traces': 'peanuts',
      'crossContamination': ['peanuts'],
      'isAustralianProduct': true,
      'image': null,
    },
    '9310015246142': {
      'name': 'Tostitos Lightly Salted Corn Chips',
      'brand': 'Tostitos',
      'ingredients': [
        'corn',
        'canola oil',
        'salt',
        'sunflower oil',
        'antioxidants (tocopherols, ascorbic acid, rosemary extract, citric acid)',
      ],
      'allergens': [],
      'mayContainItems': [],
      'crossContamination': [],
      'isAustralianProduct': true,
      'image': null,
    },
    '9310072028866': {
      'name': 'Arnott\'s Shapes Originals Barbecue',
      'brand': 'Arnott\'s',
      'ingredients': [
        'wheat flour',
        'vegetable oil',
        'starch (wheat)',
        'salt',
        'tomato powder',
        'yeast',
        'garlic',
        'parsley',
        'sugar',
        'worcestershire sauce',
        'onion powder',
        'baking powder',
        'natural flavour',
        'vegetable protein extract (from corn)',
        'spices',
        'antioxidants (e300, e307b from soy, e304)',
        'flavour enhancer (e635)',
        'emulsifier (soy lecithin)',
        'malt extract (from barley)',
      ],
      'allergens': ['gluten', 'wheat', 'soy', 'barley'],
      'mayContainItems': ['Egg', 'Milk', 'Tree Nuts', 'Peanuts', 'Sesame'],
      'traces_tags': [
        'en:eggs',
        'en:milk',
        'en:nuts',
        'en:peanuts',
        'en:sesame-seeds',
      ],
      'traces': 'eggs, milk, nuts, peanuts, sesame seeds',
      'crossContamination': ['egg', 'milk', 'tree nuts', 'peanuts', 'sesame'],
      'isAustralianProduct': true,
      'image': null,
    },
    '9310072023496': {
      'name': 'Arnott\'s Iced VoVo',
      'brand': 'Arnott\'s',
      'ingredients': [
        'sugar',
        'wheat flour',
        'raspberry flavoured filling (sugar, apple, glucose (from wheat), raspberries, fruit fibre, gelling agent (pectin), food acids, colours)',
        'desiccated coconut',
        'vegetable oil (contains soy)',
        'milk solids',
        'gelatine',
        'salt',
        'baking powder',
        'emulsifier (soy lecithin)',
        'flavours',
        'colours',
      ],
      'allergens': ['gluten', 'wheat', 'milk', 'soy'],
      'mayContainItems': ['Egg', 'Tree Nuts', 'Peanuts', 'Sesame'],
      'traces_tags': ['en:eggs', 'en:nuts', 'en:peanuts', 'en:sesame-seeds'],
      'traces': 'eggs, nuts, peanuts, sesame seeds',
      'crossContamination': ['egg', 'tree nuts', 'peanuts', 'sesame'],
      'isAustralianProduct': true,
      'image': null,
    },
    '9310015248788': {
      'name': 'Twisties Cheese',
      'brand': 'Twisties',
      'ingredients': [
        'cereals (corn (52%), rice)',
        'canola oil',
        'maltodextrin',
        'whey powder (milk)',
        'cheese powder (milk)',
        'salt',
        'flavour enhancer (621)',
        'hydrolysed vegetable protein',
        'yeast and yeast extracts',
        'mineral salt (potassium chloride)',
        'food acid (lactic acid)',
        'natural flavours (milk)',
        'natural colour (paprika extract)',
      ],
      'allergens': ['milk', 'gluten', 'soy'],
      'mayContainItems': [],
      'crossContamination': [],
      'isAustralianProduct': true,
      'image': null,
    },
    '9310072029559': {
      'name': 'Arnott\'s Tiny Teddy',
      'brand': 'Arnott\'s',
      'ingredients': [
        'wheat flour',
        'sugar',
        'vegetable oil (contains soy)',
        'milk solids',
        'cocoa butter',
        'butter (milk)',
        'vegetable fibre',
        'cocoa mass',
        'honey',
        'salt',
        'golden syrup',
        'emulsifiers (soy lecithin, e476)',
        'baking powder',
        'flavour',
      ],
      'allergens': ['gluten', 'wheat', 'milk', 'soy'],
      'mayContainItems': ['Egg', 'Tree Nuts', 'Peanuts', 'Sesame'],
      'traces_tags': [
        'en:eggs',
        'en:nuts',
        'en:peanuts',
        'en:sesame-seeds',
      ],
      'traces': 'eggs, nuts, peanuts, sesame seeds',
      'crossContamination': ['egg', 'tree nuts', 'peanuts', 'sesame'],
      'isAustralianProduct': true,
      'image': null,
    },

    // -------------------------------------------------------------------------
    // Additional OFF-verified Australian supermarket barcodes (Sep 2026).
    // -------------------------------------------------------------------------
    '9310072014753': {
      'name': 'Arnott\'s Vita-Weat 9 Grains',
      'brand': 'Arnott\'s',
      'ingredients': [
        'Crispbread Wholegrains (86%) (Wheat, Barley, Rye, Corn)',
        'Seeds (5%) (Canola, Linseed, Poppy, Sunflower Kernels)',
        'Vegetable Oil',
        'Salt',
        'Sugar',
        'Soy',
      ],
      'allergens': ['gluten', 'soy', 'wheat'],
      'mayContainItems': ['Egg', 'Milk', 'Tree Nuts', 'Peanuts', 'Sesame'],
      'traces_tags': [
        'en:eggs',
        'en:milk',
        'en:nuts',
        'en:peanuts',
        'en:sesame-seeds',
      ],
      'traces': 'eggs, milk, nuts, peanuts, sesame seeds',
      'crossContamination': ['egg', 'milk', 'tree nuts', 'peanuts', 'sesame'],
      'isAustralianProduct': true,
      'image': 'https://images.openfoodfacts.org/images/products/931/007/201/4753/front_en.79.400.jpg',
    },

    '9310072009544': {
      'name': 'Arnott\'s Chocolate Scotch Finger',
      'brand': 'Arnott\'s',
      'ingredients': [
        'Wheat Flour',
        'Sugar',
        'Butter (Cream (From Milk), Salt)',
        'Vegetable Oil (Contains Soy)',
        'Milk Solids',
        'Cocoa Butter',
        'Cocoa Mass',
        'Condensed Milk',
        'Salt',
        'Eggs',
        'Baking Powder',
        'Emulsifiers (Soy Lecithin, E476)',
        'Flavour',
      ],
      'allergens': ['egg', 'gluten', 'milk', 'soy', 'wheat'],
      'mayContainItems': ['Tree Nuts', 'Peanuts', 'Sesame'],
      'traces_tags': [
        'en:nuts',
        'en:peanuts',
        'en:sesame-seeds',
      ],
      'traces': 'nuts, peanuts, sesame seeds',
      'crossContamination': ['tree nuts', 'peanuts', 'sesame'],
      'isAustralianProduct': true,
      'image': 'https://images.openfoodfacts.org/images/products/931/007/200/9544/front_en.40.400.jpg',
    },

    '9310055102699': {
      'name': 'Kellogg\'s Corn Flakes',
      'brand': 'Kellogg\'s',
      'ingredients': [
        'Corn (90%)',
        'sugar',
        'salt',
        'barley malt extract',
        'vitamins (vitamin e, niacin, vitamin b6, riboflavin, folate)',
        'minerals (iron, zinc oxide)',
      ],
      'allergens': ['gluten', 'barley'],
      'mayContainItems': ['Tree Nuts', 'Peanuts'],
      'traces_tags': [
        'en:nuts',
        'en:peanuts',
      ],
      'traces': 'nuts, peanuts',
      'crossContamination': ['tree nuts', 'peanuts'],
      'isAustralianProduct': true,
      'image': 'https://images.openfoodfacts.org/images/products/931/005/510/2699/front_en.3.400.jpg',
    },

    '9310055536579': {
      'name': 'Kellogg\'s Crunchy Nut Corn Flakes',
      'brand': 'Kellogg\'s',
      'ingredients': [
        'Corn (55%)',
        'sugar',
        'peanuts (7.5%)',
        'honey (2%)',
        'molasses',
        'salt',
        'barley malt extract',
        'vitamins (vitamin C, vitamin E [soy], niacin, thiamin, riboflavin, folate)',
        'minerals (iron, zinc oxide)',
      ],
      'allergens': ['gluten', 'peanuts', 'soy', 'barley'],
      'mayContainItems': ['Tree Nuts'],
      'traces_tags': [
        'en:nuts',
      ],
      'traces': 'nuts',
      'crossContamination': ['tree nuts'],
      'isAustralianProduct': true,
      'image': 'https://images.openfoodfacts.org/images/products/931/005/553/6579/front_en.31.400.jpg',
    },

    '9350177000275': {
      'name': 'Sirena Tuna in Oil Italian Style',
      'brand': 'Sirena',
      'ingredients': [
        'Tuna 71% (pole & line caught yellowfin)',
        'Oil 17.2% (sunflower and extra virgin olive oil)',
        'water',
        'sea salt',
      ],
      'allergens': ['fish'],
      'mayContainItems': [],
      'crossContamination': [],
      'isAustralianProduct': true,
      'image': null,
    },

    '9350177000046': {
      'name': 'Sirena Soy & Ginger Tuna',
      'brand': 'Sirena',
      'ingredients': [
        'Pole & Line Caught Yellowfin Tuna (Fish) (65%)',
        'Oil (Sunflower Oil & Extra Virgin Olive Oil) (19%)',
        'Soy Sauce (Water, Soybeans, Wheat, And Salt) (9.5%)',
        'Ginger (6%)',
        'Sea Salt',
      ],
      'allergens': ['fish', 'gluten', 'soy', 'wheat'],
      'mayContainItems': [],
      'crossContamination': [],
      'isAustralianProduct': true,
      'image': 'https://images.openfoodfacts.org/images/products/935/017/700/0046/front_en.3.400.jpg',
    },

    '9300617307945': {
      'name': 'Cadbury Picnic Choc Cookie',
      'brand': 'Cadbury',
      'ingredients': [
        'Sugar',
        'Peanuts',
        'Glucose Syrup',
        'Milk Solids',
        'Sweetened Condensed Milk (Milk, Sugar, Milk Solids)',
        'Cookie Pieces (Wheat Flour, Sugar, Vegetable Fat, Cocoa Powder, Raising Agents (500, 503), Salt)',
        'Cocoa Butter',
        'Vegetable Fat',
        'Cocoa Mass',
        'Wheat Flour',
        'Cornstarch',
        'Emulsifiers (Soy Lecithin, 471, 476, Lecithin)',
        'Salt',
        'Cocoa Powder',
        'Vegetable Oil',
        'Flavours',
        'Raising Agent (500)',
        'Enzymes (Contain Wheat)',
      ],
      'allergens': ['gluten', 'milk', 'peanuts', 'soy', 'wheat'],
      'mayContainItems': [],
      'crossContamination': [],
      'isAustralianProduct': true,
      'image': 'https://images.openfoodfacts.org/images/products/930/061/730/7945/front_en.6.400.jpg',
    },

    '9300617065920': {
      'name': 'Cadbury Old Gold Dark Chocolate 70%',
      'brand': 'Cadbury',
      'ingredients': [
        'Cocoa Mass',
        'Sugar',
        'Cocoa Powder',
        'Cocoa Butter',
        'Flavour',
        'Milk Solids',
      ],
      'allergens': ['milk'],
      'mayContainItems': ['Gluten', 'Tree Nuts', 'Peanuts', 'Soy'],
      'traces_tags': [
        'en:gluten',
        'en:nuts',
        'en:peanuts',
        'en:soybeans',
      ],
      'traces': 'gluten, nuts, peanuts, soybeans',
      'crossContamination': ['gluten', 'tree nuts', 'peanuts', 'soy'],
      'isAustralianProduct': true,
      'image': 'https://images.openfoodfacts.org/images/products/930/061/706/5920/front_en.59.400.jpg',
    },

    '9300652810363': {
      'name': 'Sanitarium Up&Go Vanilla',
      'brand': 'Sanitarium',
      'ingredients': [
        'Water',
        'skim milk powder',
        'soy protein',
        'wheat maltodextrin',
        'cane sugar',
        'milk protein concentrate',
        'vegetable oils (sunflower, canola)',
        'plant fibre',
        'fructose',
        'flavours',
        'acidity regulator (potassium citrate)',
        'vegetable gums (460, 466, 407)',
        'mineral (calcium)',
        'stabiliser (452)',
        'vitamins (C B3, A, D2, B2, B1, B12, B6)',
        'salt',
      ],
      'allergens': ['gluten', 'milk', 'soy', 'wheat'],
      'mayContainItems': [],
      'crossContamination': [],
      'isAustralianProduct': true,
      'image': 'https://images.openfoodfacts.org/images/products/930/065/281/0363/front_en.3.400.jpg',
    },

    '9300652809169': {
      'name': 'Weet-Bix Bites Vanilla and Coconut',
      'brand': 'Sanitarium',
      'ingredients': [
        'cereals (76%) [wholegrain wheat (70%), rice flour]',
        'sugar',
        'coconut (4%)',
        'salt',
        'barley malt extract',
        'natural flavour',
        'honey',
        'vitamins (niacin, e, thiamin, riboflavin, folate)',
        'mineral (iron)',
      ],
      'allergens': ['gluten', 'wheat', 'barley'],
      'mayContainItems': ['Lupin', 'Tree Nuts', 'Sesame'],
      'traces_tags': [
        'en:lupin',
        'en:nuts',
        'en:sesame-seeds',
      ],
      'traces': 'lupin, nuts, sesame seeds',
      'crossContamination': ['lupin', 'tree nuts', 'sesame'],
      'isAustralianProduct': true,
      'image': 'https://images.openfoodfacts.org/images/products/930/065/280/9169/front_en.8.400.jpg',
    },

    '9300657234706': {
      'name': 'Heinz Baked Beans in Tomato Sauce',
      'brand': 'Heinz',
      'ingredients': [
        'Navy Beans (50%)',
        'Tomato Sauce (50%) [Tomatoes (26%), Water, Sugar, Maize Thickener (1422), Salt, Food Acid (Acetic Acid), Flavours]',
      ],
      'allergens': [],
      'mayContainItems': ['Soy'],
      'traces_tags': [
        'en:soybeans',
      ],
      'traces': 'soybeans',
      'crossContamination': ['soy'],
      'isAustralianProduct': true,
      'image': 'https://images.openfoodfacts.org/images/products/930/065/723/4706/front_en.8.400.jpg',
    },

    '9310264913444': {
      'name': 'Bega Farmers\' Tasty Natural Cheese Slices',
      'brand': 'Bega',
      'ingredients': [
        'Milk',
        'salt',
        'cultures (milk)',
        'enzyme (non-animal rennet)',
      ],
      'allergens': ['milk'],
      'mayContainItems': [],
      'crossContamination': [],
      'isAustralianProduct': true,
      'image': 'https://images.openfoodfacts.org/images/products/931/026/491/3444/front_en.3.400.jpg',
    },

    '9310264109618': {
      'name': 'Bega Farmers\' Tasty Lactose Free Cheese',
      'brand': 'Bega',
      'ingredients': [
        'Cheddar cheese [milk, salt, cultures, enzyme (non-animal rennet)]',
        'anticaking agent (460)',
        'preservative (200)',
      ],
      'allergens': ['milk'],
      'mayContainItems': [],
      'crossContamination': [],
      'isAustralianProduct': true,
      'image': 'https://images.openfoodfacts.org/images/products/931/026/410/9618/front_en.3.400.jpg',
    },

    '9310174157488': {
      'name': 'McCain SuperFries',
      'brand': 'McCain',
      'ingredients': [
        'potato (95%)',
        'canola oil',
        'dextrose',
      ],
      'allergens': [],
      'mayContainItems': [],
      'crossContamination': [],
      'isAustralianProduct': true,
      'image': 'https://images.openfoodfacts.org/images/products/931/017/415/7488/front_en.5.400.jpg',
    },

    '9310128002314': {
      'name': 'Helga\'s Light Rye Bread',
      'brand': 'Helga\'s',
      'ingredients': [
        'Wheat flour',
        'water',
        'rye flour',
        'canola oil',
        'vinegar',
        'wheat gluten',
        'soy flour',
        'iodised salt',
        'yeast',
        'fermented wheat flour',
        'malted barley flour',
        'vegetable emulsifiers (471, 472e, 481)',
        'vitamins (thiamin, folic acid)',
        'processing aids (wheat)',
      ],
      'allergens': ['gluten', 'soy', 'wheat', 'barley', 'rye'],
      'mayContainItems': ['Sesame'],
      'traces_tags': [
        'en:sesame-seeds',
      ],
      'traces': 'sesame seeds',
      'crossContamination': ['sesame'],
      'isAustralianProduct': true,
      'image': 'https://images.openfoodfacts.org/images/products/931/012/800/2314/front_en.29.400.jpg',
    },

    '9310128002536': {
      'name': 'Helga\'s Wholemeal Grain Bread',
      'brand': 'Helga\'s',
      'ingredients': [
        'Wholemeal Wheat Flour (53%)',
        'Water',
        'Wheat Flour',
        'Whole Grains (10%) [Kibbled Rye, Kibbled Triticale (Rye, Wheat), Kibbled Wheat, Wheat Flakes]',
        'Yeast',
        'Brown Linseeds',
        'Vinegar',
        'Canola Oil',
        'Iodised Salt',
        'Wheat Gluten',
        'Cultured Wheat Flour',
        'Soy Flour',
        'Malted Barley Flour',
        'Vegetable Emulsifiers (471, 472e, 481)',
        'Vitamins (Thiamin, Folic Acid)',
        'Processing Aids (Wheat)',
      ],
      'allergens': ['gluten', 'soy', 'wheat', 'barley', 'rye'],
      'mayContainItems': ['Sesame'],
      'traces_tags': [
        'en:sesame-seeds',
      ],
      'traces': 'sesame seeds',
      'crossContamination': ['sesame'],
      'isAustralianProduct': true,
      'image': 'https://images.openfoodfacts.org/images/products/931/012/800/2536/front_en.15.400.jpg',
    },

    '9310128002543': {
      'name': 'Helga\'s Mixed Grain Bread',
      'brand': 'Helga\'s',
      'ingredients': [
        'Wheat flour',
        'water',
        'mixed grains (17%) [purple wheat, kibbled wheat, kibbled rye, kibbled triticale (rye, wheat), oats]',
        'linseeds',
        'kibbled soy',
        'yeast',
        'vinegar',
        'iodised salt',
        'canola oil',
        'cultured wheat flour',
        'wheat gluten',
        'soy flour',
        'malted barley flour',
        'vegetable emulsifiers (471, 472e, 481)',
        'vitamins (thiamin, folic acid)',
        'processing aids (wheat)',
      ],
      'allergens': ['gluten', 'soy', 'wheat', 'barley', 'rye', 'oats'],
      'mayContainItems': ['Sesame'],
      'traces_tags': [
        'en:sesame-seeds',
      ],
      'traces': 'sesame seeds',
      'crossContamination': ['sesame'],
      'isAustralianProduct': true,
      'image': 'https://images.openfoodfacts.org/images/products/931/012/800/2543/front_en.39.400.jpg',
    },

    '9352042000342': {
      'name': 'Vegemite',
      'brand': 'Bega',
      'ingredients': [
        'Yeast Extract (From Yeast Grown On Barley And Wheat)',
        'Salt',
        'Mineral Salt (508)',
        'Malt Extract (From Barley)',
        'Colour (150c)',
        'Flavours',
        'Niacin',
        'Thiamine',
        'Riboflavin',
        'Folate',
      ],
      'allergens': ['gluten', 'wheat', 'barley'],
      'mayContainItems': [],
      'crossContamination': [],
      'isAustralianProduct': true,
      'image': 'https://images.openfoodfacts.org/images/products/935/204/200/0342/front_en.42.400.jpg',
    },

    '9300652010374': {
      'name': 'Weet-Bix',
      'brand': 'Sanitarium',
      'ingredients': [
        'wholegrain wheat (97%)',
        'raw sugar',
        'salt',
        'malt extract',
        'vitamins (b3, b1,b2, folic acid)',
        'minerals (iron)',
      ],
      'allergens': ['gluten', 'wheat'],
      'mayContainItems': ['Soy'],
      'traces_tags': [
        'en:soybeans',
      ],
      'traces': 'soybeans',
      'crossContamination': ['soy'],
      'isAustralianProduct': true,
      'image': 'https://images.openfoodfacts.org/images/products/930/065/201/0374/front_en.83.400.jpg',
    },

    '9300658228537': {
      'name': 'Farmers Union Greek Style Yoghurt',
      'brand': 'Farmers Union',
      'ingredients': [
        'Milk',
        'Milk Solids',
        'Cream',
        'Yogurt Cultures: S. Thermophilus & L. Bulgaricus',
      ],
      'allergens': ['milk'],
      'mayContainItems': [],
      'crossContamination': [],
      'isAustralianProduct': true,
      'image': 'https://images.openfoodfacts.org/images/products/930/065/822/8537/front_en.75.400.jpg',
    },

    '9310015232343': {
      'name': 'Smith\'s Thinly Cut Original Chips',
      'brand': 'Smith\'s',
      'ingredients': [
        'Potatoes',
        'Canola Oil',
        'Sunflower Oil',
        'Salt',
        'Antioxidants (Tocopherols, Ascorbic Acid, Rosemary Extract, Citric Acid)',
      ],
      'allergens': [],
      'mayContainItems': [],
      'crossContamination': [],
      'isAustralianProduct': true,
      'image': 'https://images.openfoodfacts.org/images/products/931/001/523/2343/front_en.13.400.jpg',
    },

    '9310015243509': {
      'name': 'Smith\'s Thinly Cut Sweet Chilli & Sour Cream Chips',
      'brand': 'Smith\'s',
      'ingredients': [
        'Potatoes',
        'Canola Oil',
        'Sunflower Oil',
        'Sugar',
        'Salt',
        'Food Acids (Sodium Diacetate, Citric Acid)',
        'Buttermilk Powder (Milk)',
        'Sour Cream Powder (Milk)',
        'Yeast Extract',
        'Mineral Salt (Potassium Chloride)',
        'Onion Powder',
        'Garlic Powder',
        'Spices (Chilli, Paprika)',
        'Corn Starch',
        'Tomato Powder',
        'Natural Colours (Paprika Extract Cochineal, Caramel)',
        'Natural Flavours',
        'Antioxidants (Tocopherols, Ascorbic Acid)',
        'Rosemary Extract',
      ],
      'allergens': ['milk'],
      'mayContainItems': ['Soy'],
      'traces_tags': [
        'en:soybeans',
      ],
      'traces': 'soybeans',
      'crossContamination': ['soy'],
      'isAustralianProduct': true,
      'image': 'https://images.openfoodfacts.org/images/products/931/001/524/3509/front_en.4.400.jpg',
    },

    '9310015232350': {
      'name': 'Smith\'s Thinly Cut Salt & Vinegar Chips',
      'brand': 'Smith\'s',
      'ingredients': [
        'Potatoes (61%)',
        'Canola Oil And/Or Sunflower Oil',
        'Natural Flavours',
        'Mineral Salt (Potassium Chloride)',
        'Salt',
        'Lactose (Milk)',
        'Maltodextrin',
        'Dextrose',
        'Sugar',
        'Soluble Fibre (Polydextrose)',
        'Food Acid (Citric Acid)',
        'Whey Protein Concentrate (Milk)',
        'Antioxidants (Tocopherols, Ascorbic Acid, Rosemary Extract)',
      ],
      'allergens': ['milk', 'soy'],
      'mayContainItems': [],
      'crossContamination': [],
      'isAustralianProduct': true,
      'image': 'https://images.openfoodfacts.org/images/products/931/001/523/2350/front_en.20.400.jpg',
    },

    '9310015233623': {
      'name': 'Smith\'s Cheese & Onion Chips',
      'brand': 'Smith\'s',
      'ingredients': [
        'Potatoes (61%)',
        'Canola Oil And/Or Sunflower Oil',
        'Whey Powder (Milk)',
        'Cheese Powder (Milk)',
        'Salt',
        'Maltodextrin',
        'Onion Powder',
        'Dextrose',
        'Mineral Salt (Potassium Chloride)',
        'Flavour Enhancer (621)',
        'Natural Flavours (Milk)',
        'Yeast Extract',
        'Food Acids (Citric Acid, Sodium Diacetate)',
        'Cream Powder (Milk)',
        'Antioxidants (Tocopherols, Ascorbic Acid, Rosemary Extract)',
      ],
      'allergens': ['milk', 'soy'],
      'mayContainItems': [],
      'crossContamination': [],
      'isAustralianProduct': true,
      'image': 'https://images.openfoodfacts.org/images/products/931/001/523/3623/front_en.5.400.jpg',
    },

    // Pack photo on Open Food Facts (structured ingredients were empty).
    '9310155012478': {
      'name': 'The Big Cheese XL Mac & Cheese',
      'brand': 'The Big Cheese',
      'ingredients': [
        'Pasta (83%) (durum wheat semolina)',
        'modified starch (1442)',
        'cheese powder (6%) (milk solids, cheese solids, salt, acidity regulators, flavour)',
        'cheese flavour (2.6%) (whey, buttermilk, milk powder, cheese solids, hydrolysed soy protein)',
        'starches',
        'salt',
        'maltodextrin',
        'sugar',
        'buttermilk powder',
        'emulsifier (322) (soy)',
        'vegetable oil',
        'hydrolysed vegetable protein (soy)',
        'colour (160b)',
      ],
      'allergens': ['wheat', 'gluten', 'milk', 'soy'],
      'mayContainItems': [],
      'crossContamination': [],
      'isAustralianProduct': true,
      'image':
          'https://images.openfoodfacts.org/images/products/931/015/501/2478/front_en.3.400.jpg',
    },

    // -------------------------------------------------------------------------
    // Offline demo aliases (synthetic barcodes kept for existing tests).
    // Same product identity as the real-barcode curated entries above.
    // -------------------------------------------------------------------------
    '9300605000000': {
      'name': 'Arnott\'s Tim Tam Original',
      'brand': 'Arnott\'s',
      'ingredients': [
        'milk chocolate (38%) (sugar, milk solids, cocoa butter, cocoa mass, vegetable oil, emulsifiers (soy lecithin, e476), flavour)',
        'wheat flour',
        'sugar',
        'vegetable oil (contains soy)',
        'golden syrup',
        'food colours (caramel iii, beet red, cochineal, annatto)',
        'cocoa powder',
        'salt',
        'baking powder',
        'emulsifier (soy lecithin)',
        'flavour',
      ],
      'allergens': ['gluten', 'milk', 'soy', 'wheat'],
      'mayContainItems': ['Egg', 'Tree Nuts', 'Peanuts', 'Sesame'],
      'crossContamination': ['egg', 'tree nuts', 'peanuts', 'sesame'],
      'isAustralianProduct': true,
      'image': null,
      'demoAliasFor': '9310072010816',
    },
    '9300605000001': {
      'name': 'Vegemite',
      'brand': 'Bega',
      'ingredients': [
        'yeast extract (from barley and wheat)',
        'salt',
        'mineral salt (508)',
        'malt extract (from barley)',
        'colour (150c)',
        'flavours',
        'niacin',
        'thiamine',
        'riboflavin',
        'folate',
      ],
      'allergens': ['gluten', 'wheat', 'barley'],
      'mayContainItems': [],
      'crossContamination': [],
      'isAustralianProduct': true,
      'image': null,
      'demoAliasFor': '9352042000328',
    },
    '9300605000002': {
      'name': 'Weet-Bix',
      'brand': 'Sanitarium',
      'ingredients': [
        'wholegrain wheat (97%)',
        'raw sugar',
        'salt',
        'barley malt extract',
        'vitamins (niacin, thiamin, riboflavin, folate)',
        'mineral (iron)',
      ],
      'allergens': ['wheat', 'gluten', 'barley'],
      'mayContainItems': ['Lupin'],
      'crossContamination': ['lupin'],
      'isAustralianProduct': true,
      'image': null,
      'demoAliasFor': '9300652010794',
    },
    '9300605000003': {
      'name': 'Cadbury Dairy Milk Chocolate',
      'brand': 'Cadbury',
      'ingredients': [
        'full cream milk',
        'sugar',
        'cocoa mass',
        'milk solids',
        'cocoa butter',
        'emulsifiers (soy lecithin, 476)',
        'flavours',
        'may contain wheat, gluten, peanuts, tree nuts',
      ],
      'allergens': ['milk', 'soy'],
      'mayContainItems': ['Wheat', 'Gluten', 'Peanuts', 'Tree Nuts'],
      'crossContamination': ['wheat', 'gluten', 'peanuts', 'tree nuts'],
      'isAustralianProduct': true,
      'image': null,
      'demoAliasFor': '9300617304715',
    },
    '9300605000004': {
      'name': 'Bega Peanut Butter Crunchy',
      'brand': 'Bega',
      'ingredients': [
        'roasted peanuts (86%)',
        'vegetable oil (antioxidant (320))',
        'sugar',
        'salt',
      ],
      'allergens': ['peanuts'],
      'mayContainItems': ['Tree Nuts', 'Sesame'],
      'crossContamination': ['tree nuts', 'sesame'],
      'isAustralianProduct': true,
      'image': null,
      'demoAliasFor': '9352042002827',
    },
  };

  static int get count => products.length;

  static List<String> get barcodes => products.keys.toList();

  /// Pack ingredient list from the user's Arnott's Bizza Shapes label.
  static Map<String, dynamic> _arnottsBizzaShapes() {
    return {
      'name': 'Arnott\'s Bizza Shapes',
      'brand': 'Arnott\'s',
      'ingredients': [
        'wheat flour',
        'vegetable oil (antioxidant 307b from Soy)',
        'salt',
        'tomato powder',
        'starches (maize, wheat)',
        'maltodextrin',
        'cheese (milk)',
        'yeast',
        'dried parsley',
        'glucose',
        'raising agents (500,341)',
        'onion powder',
        'milk solids',
        'sugar',
        'garlic powder',
        'spices',
        'hydrolysed vegetable protein (from soy)',
        'mustard powder',
        'food acid (citric acid)',
        'flavour (contains milk)',
        'basil',
        'antioxidant (ascorbic acid)',
        'spice extracts',
        'yeast extract',
        'flavour enhancer (635)',
        'lemon oil',
        'mustard seed oil',
        'herb extract',
        'food colours (paprika extract, tumeric)',
      ],
      'allergens': ['wheat', 'gluten', 'milk', 'soy'],
      'mayContainItems': ['Egg', 'Tree Nuts', 'Peanut', 'Sesame'],
      'traces_tags': [
        'en:eggs',
        'en:tree-nuts',
        'en:peanuts',
        'en:sesame-seeds',
      ],
      'traces': 'eggs, tree nuts, peanuts, sesame seeds',
      'crossContamination': ['egg', 'tree nuts', 'peanut', 'sesame'],
      'isAustralianProduct': true,
      'image': null,
    };
  }
}
