class Allergen {
  final String name;
  final String category;
  final bool isPro;

  Allergen({
    required this.name,
    required this.category,
    this.isPro = false,
  });
}

// Basic allergens (free tier)
final Map<String, List<String>> basicAllergenCategories = {
  'Food': [
    'Peanuts',
    'Milk',
    'Pecan',
    'Wheat',
    'Soy',
    'Banana',
    'Celery',
  ],
};

// Pro allergens (additional categories)
final Map<String, List<String>> proAllergenCategories = {
  'Nuts & Seeds': [
    'Peanuts',
    'Almond',
    'Cashew',
    'Hazelnut',
    'Pecan',
    'Walnut',
    'Brazil Nut',
    'Pistachio',
    'Macadamia',
    'Pine Nut',
    'Coconut',
    'Sesame',
    'Chestnut',
  ],
  'Dairy Products': [
    'Milk',
    'Casein',
    'Whey',
    'Egg',
  ],
  'Grains & Wheat': [
    'Wheat',
    'Gluten',
    'Corn',
    'Rice',
    'Oats',
    'Barley',
    'Rye',
    'Quinoa',
    'Buckwheat',
  ],
  'Legumes & Soy': [
    'Soy',
    'Lupin',
  ],
  'Seafood': [
    'Fish',
    'Shrimp',
    'Crab',
    'Lobster',
    'Oysters',
    'Mussels',
    'Clams',
    'Scallops',
    'Squid',
    'Octopus',
    'Anchovies',
    'Tuna',
    'Salmon',
    'Cod',
    'Mackerel',
    'Sardines',
    'Trout',
    'Bass',
    'Snapper',
    'Grouper',
    'Mahi Mahi',
    'Halibut',
    'Flounder',
    'Sole',
    'Perch',
    'Catfish',
    'Tilapia',
    'Sea Bass',
    'Red Snapper',
    'Yellowfin Tuna',
    'Albacore Tuna',
    'Skipjack Tuna',
    'Bluefin Tuna',
    'Atlantic Salmon',
    'Pacific Salmon',
    'Rainbow Trout',
    'Brook Trout',
    'Brown Trout',
    'Lake Trout',
    'Arctic Char',
    'Whitefish',
    'Herring',
    'Pike',
    'Walleye',
    'Bluefish',
    'Striped Bass',
    'Rockfish',
    'Monkfish',
    'Swordfish',
    'Marlin',
    'Shark',
    'Ray',
    'Eel',
    'Sea Urchin',
    'Abalone',
    'Conch',
    'Whelk',
    'Periwinkle',
    'Limpet',
    'Chiton',
  ],
  'Fruits & Vegetables': [
    'Kiwi',
    'Banana',
    'Tomato',
    'Celery',
    'Strawberry',
    'Apple',
    'Peach',
    'Pear',
    'Melon',
    'Cherry',
    'Plum',
    'Apricot',
    'Grapes',
    'Orange',
    'Lemon',
    'Lime',
    'Mandarin',
    'Mango',
    'Avocado',
    'Carrot',
    'Potato',
    'Sweet Potato',
    'Capsicum',
    'Chilli',
    'Cucumber',
    'Zucchini',
    'Peas',
    'Lentils',
    'Chickpeas',
    'Spinach',
    'Lettuce',
  ],
};

// Combined map for reference
final Map<String, List<String>> allergenCategories = {
  ...basicAllergenCategories,
  ...proAllergenCategories,
};
